spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    driverClassName: org.postgresql.Driver
    url: not_set
    username: not_set
    password: not_set

    hikari:
      data-source-properties:
        stringtype: unspecified
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        maintainTimeStats: false
        maximum-pool-size: 5
        connection-timeout: 5000
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: false
    open-in-view: false
    generate-ddl: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

  devtools:
    restart:
      additional-paths: src/main/webapp
      exclude: static/**,public/**

server:
  port: not_set
  error:
    include-message: always

spring.data.redis:
  repositories.enabled: false
  host: not_set
  password: not_set
  port: not_set

client:
  api_urls:
    client_search_api: not_set

keycloak:
  from_dc:
    url: not_set
    clientId: not_set
    clientSecret: not_set
  dp:
    url: not_set
    username: not_set
    password: not_set
    master:
      url: not_set
      getClientUrl: not_set
      clientId: not_set
      clientSecret: not_set
    client:
      url: not_set
      realm: not_set
      clientId: not_set
      clientSecret: not_set
      realmClientId: not_set
      realmClientSecret: not_set

crypto:
  to_dc:
    support_encryption: not_set
    support_signature: not_set
    password: not_set
    key_path: not_set
    id: not_set
  from_dc:
    support_encryption: not_set
    support_signature: not_set
    password: not_set
    key_path: not_set

dashboard:
  dp_dashboard_url: not_set