spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dp1?currentSchema=g2pc
    username: postgres
    password: postgres
    hikari:
      data-source-properties:
        stringtype: unspecified
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        maintainTimeStats: false
        maximum-pool-size: 5
        connection-timeout: 5000
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: false
    open-in-view: false
    generate-ddl: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

  devtools:
    restart:
      additional-paths: src/main/webapp
      exclude: static/**,public/**

server:
  port: 9001
  error:
    include-message: always

spring.data.redis:
  repositories.enabled: false
  host: localhost
  password: 123456789
  port: 6379

client:
  api_urls:
    client_search_api: "http://localhost:8000/private/api/v1/registry/on-search"
    client_search_public_api: "http://localhost:8000/public/api/v1/registry/on-search"

keycloak:
  data-consumer:
    url: "http://127.0.0.1:8081/auth/realms/data-consumer/protocol/openid-connect/token"
    client-id: dc-client
    client-secret: 82sb19hilQNGFBixW5AJInBHb0Xx2j6K
  farmer:
    admin-url: http://127.0.0.1:8081/auth/realms/master/protocol/openid-connect/token
    get-client-url: http://127.0.0.1:8081/auth/admin/realms/dp-farmer/clients
  realm: dp-farmer
  url: http://127.0.0.1:8081/auth
  admin:
    client-id: admin-cli
    client-secret: D50Wdnxc7JiQxCPi884aVDAiQy1nfPpq

crypto:
  consumer:
    support_encryption: true
    support_signature: true
  farmer:
    support_encryption: true
    support_signature: true