
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://g2pc-spec-demo-rds.cs9zoco3zxkq.ap-south-1.rds.amazonaws.com:5432/dp1?currentSchema=g2pc
    username: postgres
    password: K6tnrCU0wqXOwPW
    hikari:
      data-source-properties:
        stringtype: unspecified
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        maintainTimeStats: false
        maximum-pool-size: 5
        connection-timeout: 5000
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: false
    open-in-view: false
    generate-ddl: false

spring.data.redis:
  repositories.enabled: false
  host: localhost
  password: 123456789
  port: 6376

crypto:
  to_dc:
    support_encryption: true
    support_signature: true
    password: "farmer_on_search"
    key_path: "classpath:farmer_on_search.p12"
    id: FARMER
  from_dc:
    support_encryption: true
    support_signature: true
    password: "farmer_search"
    key_path: "classpath:farmer_search.p12"

client:
  api_urls:
    client_search_api: "http://localhost:8000/private/api/v1/registry/on-search"
    client_status_api: "http://localhost:8000/private/api/v1/registry/on-status"

keycloak:
  from_dc:
    url: "https://g2pc-dc-lab.cdpi.dev/auth/realms/data-consumer/protocol/openid-connect/token"
    clientId: dc-client
    clientSecret: co0rJfm3mIq0OXysAt6DtDjibOHkcktY
  dp:
    url: https://g2pc-dp1-lab.cdpi.dev/auth
    username: admin
    password: cdpi@9923
    master:
      url: https://g2pc-dp1-lab.cdpi.dev/auth/realms/master/protocol/openid-connect/token
      getClientUrl: https://g2pc-dp1-lab.cdpi.dev/auth/admin/realms/dp-farmer/clients
      clientId: admin-cli
      clientSecret: G7rVA27HI5UpzMJfomRvaQHubtbAcWcN
    client:
      url: https://g2pc-dp1-lab.cdpi.dev/auth/realms/dp-farmer/protocol/openid-connect/token
      realm: dp-farmer
      clientId: dp-farmer-client
      clientSecret: 55VuMuin1T8xbYSUu5zAJAebA05tSwkX

sftp:
  listener:
    host: localhost
    port: 2225
    user: cdpi
    password: 1234
    remote:
      inbound_directory: /inbound
      outbound_directory: /outbound
    local:
      inbound_directory: /home/prihir/g2pc/dp1/inbound
      outbound_directory: /home/prihir/g2pc/dp1/outbound

  dc:
    host: localhost
    port: 2224
    user: cdpi
    password: 1234
    remote:
      outbound_directory: /outbound


sunbird:
  api_urls:
    response_data_api: http://3.109.26.38:8083/api/v1/Msg_Tracker
    response_tracker_api: http://3.109.26.38:8083/api/v1/Txn_Tracker
  enabled: true
  elasticsearch:
    host: 3.109.26.38
    port: 9200
    scheme: http