spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dc1?currentSchema=g2pc
    username: postgres
    password: postgres
    hikari:
      data-source-properties:
        stringtype: unspecified
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        maintainTimeStats: false
        maximum-pool-size: 5
        connection-timeout: 5000
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: false
    open-in-view: false
    generate-ddl: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

  devtools:
    restart:
      additional-paths: src/main/webapp
      exclude: static/**,public/**

server:
  port: 8000
  error:
    include-message: always

spring.data.redis:
  repositories.enabled: false
  host: localhost
  password: 123456789
  port: 6379

  api_urls:
    #farmer_search_api: "https://webhook.site/9043a6a4-1710-4af6-a7c6-25a55c6fc903"
    #mobile_search_api: "http://localhost:9200/private/api/v1/registry/mobile/info"
    farmer_search_api: "http://localhost:9001/private/api/v1/registry/search"
    mobile_search_api: "http://localhost:9002/private/api/v1/registry/search"

keycloak:
  from_dp:
    farmer:
      url: "https://g2pc-dp1-lab.cdpi.dev/auth/realms/dp-farmer/protocol/openid-connect/token"
      clientId: "dp-farmer-client"
      clientSecret: "55VuMuin1T8xbYSUu5zAJAebA05tSwkX"
    mobile:
      url: "https://g2pc-dp2-lab.cdpi.dev/auth/realms/dp-mobile/protocol/openid-connect/token"
      clientId: "dp-mobile-client"
      clientSecret: "d9yPYp8G2nYLh1ztdeqvdvtxEYqx63Xg"
  dc:
    url: https://g2pc-dc-lab.cdpi.dev/auth
    username: admin
    password: cdpi@9922
    master:
      url: https://g2pc-dc-lab.cdpi.dev/auth/realms/master/protocol/openid-connect/token
      getClientUrl: https://g2pc-dc-lab.cdpi.dev/auth/admin/realms/data-consumer/clients
      clientId: admin-cli
      clientSecret: bCfUQy4z4NKiiz82zScJdKGtbKbchkhs
    client:
      url: https://g2pc-dc-lab.cdpi.dev/auth/realms/data-consumer/protocol/openid-connect/token
      realm: data-consumer
      clientId: dc-client
      clientSecret: co0rJfm3mIq0OXysAt6DtDjibOHkcktY

crypto:
  to_dp_farmer:
    support_encryption: true
    support_signature: true
    password: "farmer_search"
    key_path: "classpath:farmer_search.p12"
  to_dp_mobile:
    support_encryption: true
    support_signature: true
    password: "mobile_search"
    key_path: "classpath:mobile_search.p12"
  from_dp_farmer:
    support_encryption: true
    support_signature: true
    password: "farmer_on_search"
    key_path: "classpath:farmer_on_search.p12"
    id: FARMER
  from_dp_mobile:
    support_encryption: true
    support_signature: true
    password: "mobile_on_search"
    key_path: "classpath:mobile_on_search.p12"
    id: MOBILE

registry:
  api_urls:
    farmer_search_api: "http://localhost:9001/private/api/v1/registry/search"
    mobile_search_api: "http://localhost:9002/private/api/v1/registry/search"
    farmer_search_public_api: "https://g2pc-dp1-lab.cdpi.dev/dp-farmer/public/api/v1/registry/search"
    mobile_search_public_api: "https://g2pc-dp2-lab.cdpi.dev/dp-mno/public/api/v1/registry/search"

dashboard:
  left_panel_url: "http://3.109.26.38:3005/d-solo/cb26f39f-97f3-43ea-9f42-68d49d9822a3/left-panel-data?orgId=1&refresh=5s&from=1701984074137&to=1702005674137&panelId=1"
  right_panel_url: "http://3.109.26.38:3005/d-solo/d9f9c625-934b-4a65-995f-c742daad6387/right-panel-data?orgId=1&refresh=5s&from=1701984074137&to=1702005674137&panelId=1"
  bottom_panel_url: "http://3.109.26.38:3005/d-solo/a25a6c65-fda7-4fdd-80a7-80442aed17e8/bottom-panel-data?orgId=1&refresh=5s&from=1701984074137&to=1702005674137&panelId=1"
  post_endpoint_url: "https://g2pc-dc-lab.cdpi.dev/dc-client/public/api/v1/consumer/search/csv"
  clear_dc_db_endpoint_url: "https://g2pc-dc-lab.cdpi.dev/dc-client/public/api/v1/consumer/search/csv"
  clear_dp_db_endpoint_url: "https://g2pc-dc-lab.cdpi.dev/dc-client/public/api/v1/consumer/search/csv"
  post_sftp_endpoint_url: "http://localhost:8000/public/api/v1/consumer/search/sftp/csv"
