spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    driverClassName: org.postgresql.Driver
    url: not_set
    username: not_set
    password: not_set
    hikari:
      data-source-properties:
        stringtype: unspecified
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        maintainTimeStats: false
        maximum-pool-size: 5
        connection-timeout: 5000

  second-datasource:
    driverClassName: not_set
    url: not_set
    username: not_set
    password: not_set

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: false
    open-in-view: false
    generate-ddl: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

  devtools:
    restart:
      additional-paths: src/main/webapp
      exclude: static/**,public/**

server:
  port: 8000
  error:
    include-message: always

spring.data.redis:
  repositories.enabled: false
  host: not_set
  password: not_set
  port: not_set

keycloak:
  from_dp:
    farmer:
      url: not_set
      clientId: not_set
      clientSecret: not_set
    mobile:
      url: not_set
      clientId: not_set
      clientSecret: not_set
  dc:
    url: not_set
    username: not_set
    password: not_set
    master:
      url: not_set
      getClientUrl: not_set
      clientId: not_set
      clientSecret: not_set
    client:
      url: not_set
      realm: not_set
      clientId: not_set
      clientSecret: not_set

crypto:
  to_dp_farmer:
    password: not_set
    key_path: not_set
  to_dp_mobile:
    password: not_set
    key_path: not_set
  from_dp_farmer:
    password: not_set
    key_path: not_set
  from_dp_mobile:
    password: not_set
    key_path: not_set
  sample:
    password: not_set
    key.path: not_set

registry:
  api_urls:
    farmer_search_api: not_set
    mobile_search_api: not_set
    farmer_status_api: not_set
    mobile_status_api: not_set

dashboard:
  left_panel_url: not_set
  right_panel_url: not_set
  bottom_panel_url: not_set
  post_https_endpoint_url: not_set
  clear_dc_db_endpoint_url: not_set
  clear_dp1_db_endpoint_url: not_set
  clear_dp2_db_endpoint_url: not_set
  left_panel_data_endpoint_url: not_set
  sftp_post_endpoint_url: not_set
  sftp_dc_data_endpoint_url: not_set
  sftp_dp1_data_endpoint_url: not_set
  sftp_dp2_data_endpoint_url: not_set
  dc_status_endpoint_url: not_set
  sftp_left_panel_url: not_set
  sftp_right_panel_url: not_set
  sftp_bottom_panel_url: not_set
  https_sunbird_left_panel_url: not_set
  https_sunbird_right_panel_url: not_set
  https_sunbird_bottom_panel_url: not_set
  sftp_sunbird_left_panel_url: not_set
  sftp_sunbird_right_panel_url: not_set
  sftp_sunbird_bottom_panel_url: not_set

sftp:
  listener:
    host: not_set
    port: not_set
    user: not_set
    password: not_set
    remote:
      inbound_directory: not_set
      outbound_directory: not_set
    local:
      inbound_directory: not_set
      outbound_directory: not_set

  dp1:
    host: not_set
    port: not_set
    user: not_set
    password: not_set
    remote:
      inbound_directory: not_set

  dp2:
    host: not_set
    port: not_set
    user: not_set
    password: not_set
    remote:
      inbound_directory: not_set

sunbird:
  api_urls:
    response_data_api: not_set
    response_tracker_api: not_set
  elasticsearch:
    host: not_set
    port: not_set
    scheme: not_set