spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    driverClassName: org.postgresql.Driver
    url: not_set
    username: not_set
    password: not_set

    hikari:
      data-source-properties:
        stringtype: unspecified
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        maintainTimeStats: false
        maximum-pool-size: 5
        connection-timeout: 5000
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: false
    open-in-view: false
    generate-ddl: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

  devtools:
    restart:
      additional-paths: src/main/webapp
      exclude: static/**,public/**

server:
  port: 8000
  error:
    include-message: always

spring.data.redis:
  repositories.enabled: false
  host: localhost
  password: 123456789
  port: 6379

keycloak:
  from_dp:
    farmer:
      url: not_set
      clientId: not_set
      clientSecret: not_set
    mobile:
      url: not_set
      clientId: not_set
      clientSecret: not_set
  dc:
    url: not_set
    username: not_set
    password: not_set
    master:
      url: not_set
      getClientUrl: not_set
      clientId: not_set
      clientSecret: not_set
    client:
      url: not_set
      realm: not_set
      clientId: not_set
      clientSecret: not_set

crypto:
  to_dp_farmer:
    support_encryption: not_set
    support_signature: not_set
    password: not_set
    key_path: not_set
  to_dp_mobile:
    support_encryption: not_set
    support_signature: not_set
    password: not_set
    key_path: not_set
  from_dp_farmer:
    support_encryption: not_set
    support_signature: not_set
    password: not_set
    key_path: not_set
    id: not_set
  from_dp_mobile:
    support_encryption: not_set
    support_signature: not_set
    password: not_set
    key_path: not_set
    id: not_set

registry:
  api_urls:
    farmer_search_api: not_set
    mobile_search_api: not_set

dashboard:
  left_panel_url: not_set
  right_panel_url: not_set
  bottom_panel_url: not_set
  post_endpoint_url: not_set
  clear_dc_db_endpoint_url: not_set
  clear_dp1_db_endpoint_url: not_set
  clear_dp2_db_endpoint_url: not_set