spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

server:
  port: 9002
  error:
    include-message: always

spring.data.redis:
  repositories.enabled: false
  host: localhost
  password: 123456789
  port: 6379

client:
  api_urls:
    client_search_api: "http://localhost:8000/private/api/v1/registry/on-search"
    mobile_info_api: "http://localhost:9200/private/api/v1/registry/mobile/info"

keycloak:
  data-consumer:
    url: "http://127.0.0.1:8081/auth/realms/data-consumer/protocol/openid-connect/token"
    client-id: dc-client
    client-secret: 82sb19hilQNGFBixW5AJInBHb0Xx2j6K
  mobile:
    admin-url: http://127.0.0.1:8081/auth/realms/master/protocol/openid-connect/token
    get-client-url: http://127.0.0.1:8081/auth/admin/realms/dp-mobile/clients
  realm: dp-mobile
  url: http://127.0.0.1:8081/auth
  admin:
    client-id: admin-cli
    client-secret: eJ7bErtDvu0D5yXP37zLjAgGC28S1ofT

crypto:
  support_encryption: false
  support_signature: false
