spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driverClassName: org.postgresql.Driver
    url: not_set
    username: postgres
    password: not_set

    hikari:
      data-source-properties:
        stringtype: unspecified
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        maintainTimeStats: false
        maximum-pool-size: 5
        connection-timeout: 5000
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: false
    open-in-view: false
    generate-ddl: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

  devtools:
    restart:
      additional-paths: src/main/webapp
      exclude: static/**,public/**

server:
  port: 9002
  error:
    include-message: always

spring.data.redis:
  repositories.enabled: false
  host: not_set
  password: not_set
  port: 6377

client:
  api_urls:
    client_search_api: "http://localhost:8000/private/api/v1/registry/on-search"
    mno_info_url: "http://localhost:9200/private/api/v1/registry/mobile/info"

keycloak:
  data-consumer:
    url: "https://g2pc-dc-lab.cdpi.dev/auth/realms/data-consumer/protocol/openid-connect/token"
    client-id: dc-client
    client-secret: not_set
  mobile:
    admin-url: https://g2pc-dp2-lab.cdpi.dev/auth/realms/master/protocol/openid-connect/token
    get-client-url: https://g2pc-dp2-lab.cdpi.dev/auth/admin/realms/dp-mobile/clients
  realm: dp-mobile
  url: https://g2pc-dp2-lab.cdpi.dev/auth
  admin:
    realm:
      client-id: admin-cli
      client-secret: not_set
    client-id: admin-cli
    client-secret: not_set
    username: admin
    password: not_set

crypto:
  consumer:
    support_encryption: true
    support_signature: true
  mobile:
    support_encryption: true
    support_signature: true

