spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://g2pc-spec-demo-rds.cs9zoco3zxkq.ap-south-1.rds.amazonaws.com:5432/dp2?currentSchema=g2pc
    username: postgres
    password: K6tnrCU0wqXOwPW

    hikari:
      data-source-properties:
        stringtype: unspecified
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        maintainTimeStats: false
        maximum-pool-size: 5
        connection-timeout: 5000
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: false
    open-in-view: false
    generate-ddl: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

  devtools:
    restart:
      additional-paths: src/main/webapp
      exclude: static/**,public/**

server:
  port: 9002
  error:
    include-message: always

spring.data.redis:
  repositories.enabled: false
  host: 3.109.26.38
  password: cdpi@99223
  port: 6377

client:
  api_urls:
    client_search_api: "http://localhost:8000/private/api/v1/registry/on-search"
    mno_info_url: "http://localhost:9005/private/api/v1/registry/mobile/info"
    client_status_api: "http://localhost:8000/private/api/v1/registry/on-status"

keycloak:
  from-dc:
    url: "https://g2pc-dc-lab.cdpi.dev/auth/realms/data-consumer/protocol/openid-connect/token"
    client-id: dc-client
    client-secret: co0rJfm3mIq0OXysAt6DtDjibOHkcktY
  dp:
    url: https://g2pc-dp2-lab.cdpi.dev/auth
    username: admin
    password: cdpi@9924
    master:
      url: https://g2pc-dp2-lab.cdpi.dev/auth/realms/master/protocol/openid-connect/token
      getClientUrl: https://g2pc-dp2-lab.cdpi.dev/auth/admin/realms/dp-mobile/clients
      clientId: admin-cli
      clientSecret: awR1cImNnsiOnBeWpZQWUfKFr1gOopBo
    client:
      url: https://g2pc-dp2-lab.cdpi.dev/auth/realms/dp-mobile/protocol/openid-connect/token
      realm: dp-mobile
      clientId: dp-mobile-client
      clientSecret: d9yPYp8G2nYLh1ztdeqvdvtxEYqx63Xg

crypto:
  to_dc:
    support_encryption: true
    support_signature: true
    password: "mobile_on_search"
    key_path: "classpath:mobile_on_search.p12"
    id: MOBILE
  from_dc:
    support_encryption: true
    support_signature: true
    password: "mobile_search"
    key_path: "classpath:mobile_search.p12"

dashboard:
  dp_dashboard_url: "http://3.109.26.38:3005/d-solo/e62ae08b-a6e1-4095-af79-c36f02b8fae2/dp1-dashboard?orgId=1&refresh=5s&from=1701984074137&to=1702005674137&panelId=1"
  cors_origin_url: "http://localhost:8000"

sftp:
  listener:
    host: localhost
    port: 2226
    user: cdpi
    password: 1234
    remote:
      inbound_directory: /inbound
      outbound_directory: /outbound
    local:
      inbound_directory: /home/prihir/g2pc/dp2/inbound
      outbound_directory: /home/prihir/g2pc/dp2/outbound

  dc:
    host: localhost
    port: 2224
    user: cdpi
    password: 1234
    remote:
      outbound_directory: /outbound

sunbird:
  api_urls:
    response_data_api: http://3.109.26.38:8083/api/v1/Msg_Tracker
    response_tracker_api: http://3.109.26.38:8083/api/v1/Txn_Tracker
  enabled: false
  elasticsearch:
    host: 3.109.26.38
    port: 9200
    scheme: http